# Generated by Django 5.0.6 on 2024-05-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='imagenes/default.png', upload_to='imagenes/'),
        ),
    ]
