# Generated by Django 5.0.6 on 2024-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('pasillo', models.CharField(max_length=100)),
            ],
        ),
    ]
