# Generated by Django 5.0.6 on 2024-05-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0003_recepcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcion',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='inventarioweb_producto',
        ),
        migrations.AlterModelTable(
            name='recepcion',
            table='inventarioweb_recepcion',
        ),
    ]
