# Generated by Django 5.0.6 on 2024-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0005_alter_recepcion_cantidad_alter_recepcion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='movimiento',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
