# Generated by Django 5.0.6 on 2024-05-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0006_recepcion_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
