# Generated by Django 5.0.6 on 2024-05-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0007_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'inventarioweb_HistorialPrecio',
            },
        ),
    ]
