# Generated by Django 5.0.6 on 2024-05-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0008_historialprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecio',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialprecio',
            name='fecha',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='historialprecio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
