# Generated by Django 5.0.6 on 2024-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0009_historialprecio_nombre_historialprecio_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
