# Generated by Django 5.0.6 on 2024-05-22 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0010_producto_fecha_vencimiento_producto_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 18, 6, 55, 430374)),
        ),
    ]
