# Generated by Django 5.0.6 on 2024-05-22 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0012_alter_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 5, 22)),
        ),
    ]
