# Generated by Django 5.0.6 on 2024-06-01 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0013_alter_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lote',
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 6, 1)),
        ),
    ]
