# Generated by Django 5.0.6 on 2024-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0014_remove_producto_lote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=100)),
                ('movimiento', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'db_table': 'inventarioweb_envio',
            },
        ),
    ]
