# Generated by Django 5.0.6 on 2024-06-17 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioweb', '0017_alter_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='kit',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(default='imagenes/default.png', upload_to='imagenes/')),
                ('stock', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(default=datetime.date(2024, 6, 17))),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 6, 17)),
        ),
    ]
